export const careers = [
  {
    id: 1,
    title: "Senior React Developer",
    department: "Engineering",
    type: "Full-Time",
    experience: "3–5 Years",
    location: "Chennai, India",
    mode: "Hybrid",
    salary: "₹8L – ₹12L",
    posted: "2 days ago",
    skills: [
      "React",
      "JavaScript",
      "Tailwind CSS",
      "REST API",
    ],
    description:
      "Build scalable React applications and collaborate with designers and backend engineers.",
  },
  {
    id: 2,
    title: "UI / UX Designer",
    department: "Design",
    type: "Full-Time",
    experience: "2–4 Years",
    location: "Remote",
    mode: "Remote",
    salary: "₹6L – ₹9L",
    posted: "5 days ago",
    skills: [
      "Figma",
      "Adobe XD",
      "Prototyping",
      "Design Systems",
    ],
    description:
      "Create intuitive user experiences and modern interfaces for web and mobile products.",
  },
  {
    id: 3,
    title: "AI Engineer",
    department: "AI",
    type: "Full-Time",
    experience: "2–5 Years",
    location: "Bengaluru, India",
    mode: "Hybrid",
    salary: "₹10L – ₹16L",
    posted: "1 week ago",
    skills: [
      "Python",
      "TensorFlow",
      "OpenAI",
      "LangChain",
    ],
    description:
      "Develop AI-powered applications, chatbots and intelligent automation solutions.",
  },
  {
    id: 4,
    title: "Digital Marketing Executive",
    department: "Marketing",
    type: "Full-Time",
    experience: "1–3 Years",
    location: "Remote",
    mode: "Remote",
    salary: "₹4L – ₹7L",
    posted: "3 days ago",
    skills: [
      "SEO",
      "Google Ads",
      "Analytics",
      "Social Media",
    ],
    description:
      "Plan and execute digital marketing campaigns that drive growth and engagement.",
  },
  {
    id: 5,
    title: "Sales Executive",
    department: "Sales",
    type: "Full-Time",
    experience: "1–2 Years",
    location: "Coimbatore, India",
    mode: "On-site",
    salary: "₹3L – ₹6L",
    posted: "6 days ago",
    skills: [
      "CRM",
      "Communication",
      "Lead Generation",
      "Negotiation",
    ],
    description:
      "Build client relationships, generate leads and help businesses discover Riyadvi's services.",
  },
  {
    id: 6,
    title: "Software Engineering Intern",
    department: "Engineering",
    type: "Internship",
    experience: "Fresher",
    location: "Remote",
    mode: "Remote",
    salary: "Paid Internship",
    posted: "Today",
    skills: [
      "HTML",
      "CSS",
      "JavaScript",
      "React",
    ],
    description:
      "Learn modern web development while contributing to real client projects under experienced mentors.",
  },
];